/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as InvoicesRouteImport } from "./routes/invoices.route"
import { Route as IndexImport } from "./routes/index"
import { Route as InvoicesIndexImport } from "./routes/invoices.index"
import { Route as InvoicesInvoiceIdImport } from "./routes/invoices.$invoiceId"

// Create/Update Routes

const InvoicesRouteRoute = InvoicesRouteImport.update({
  path: "/invoices",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const InvoicesIndexRoute = InvoicesIndexImport.update({
  path: "/",
  getParentRoute: () => InvoicesRouteRoute,
} as any)

const InvoicesInvoiceIdRoute = InvoicesInvoiceIdImport.update({
  path: "/$invoiceId",
  getParentRoute: () => InvoicesRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/invoices": {
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRoute
    }
    "/invoices/$invoiceId": {
      preLoaderRoute: typeof InvoicesInvoiceIdImport
      parentRoute: typeof InvoicesRouteImport
    }
    "/invoices/": {
      preLoaderRoute: typeof InvoicesIndexImport
      parentRoute: typeof InvoicesRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  InvoicesRouteRoute.addChildren([InvoicesInvoiceIdRoute, InvoicesIndexRoute]),
])

/* prettier-ignore-end */
